### ISSUE TITLE
new API naming convention (from gitlab)

### ISSUE THREAD

**Issue by paldar** [cmu-sei/gbtl#14]
After the GraphBLAS API call of 2 October we have new more explicit C++ naming standards:
The namespace: GraphBLAS API operations: will be 'camelCase' except for matrix multiplies as follows: buildMatrix, mXm, extractTuples
In addition an mxm_demo.cpp must be written (adapt mxm_test.cpp) and use the specific values from the homework assignment.
This will need to committed to the API bitbucket repo.

**Comment by mcmillan03** [comment]
Closing. OBE
