### ISSUE TITLE
consider semiring in ewise* interface as an argument

### ISSUE THREAD

**Issue by paldar** [cmu-sei/gbtl#38]

**Comment by mcmillan03** [comment]
To clarify, these funtions only need BinaryFunction's to operate (structural zeros are never accessed or produced in these operations).  We can provide both BinaryFunction and Monoid objects unambiguously.  Should we support a signature that takes a Semiring then implicit logic should be document or explicit parameter must be supported to say which Monoid or BinaryFunction within the Semiring should be use.  The obvious implicit logic is for eWiseAdd to access the additive Monoid and eWiseMult to access the multiplicative Monoid/BinaryFunction.

**Comment by mcmillan03** [comment]
Accidentally closed.

**Comment by mcmillan03** [comment]
The correct way is to wrap the semiring in a "view" object that adheres to the BinaryFunction concept.  Closing this issue.
