### ISSUE TITLE
Warning: no return statement in non-void extractTuples function

### ISSUE THREAD

**Issue by phcerdan** [cmu-sei/gbtl#42]
```
../src/graphblas/platforms/sequential/LilSparseMatrix.hpp:578:13:
 warning: no return statement in function returning non-void [-Wreturn-type]

```

**Comment by mcmillan03** [comment]
Thanks for the report. Clearly it should be a void return type.  Could you provide more information about what was being compiled, your compiler version, etc?

**Comment by phcerdan** [comment]
The compiler was `gcc 9.1`, and the options were default using `CMake` with `-DCMAKE_BUILD_TYPE:STRING=Debug`

**Comment by phcerdan** [comment]
The warning `-Wreturn-type` is enabled by default in gcc (no need turning `-Wall`). Reference: https://gcc.gnu.org/onlinedocs/gcc/Warning-Options.html
```
This warning is enabled by default in C++ and by -Wall otherwise. 
```

**Comment by mcmillan03** [comment]
The default must have changed...I am using g++ 7.4 at the moment.

**Comment by mcmillan03** [comment]
I have merged changes to master branch that resolve this issue as well as remove many other compiler warnings when -Wall flag is used.  Closing issue
